language: java
script: mvn install -DskipITs
jdk:
- oraclejdk8

branches:
    only:
    - master 

notifications:
    email:
    - jinified@gmail.com 
    - zhulingjiee@gmail.com
    - woanchin.tee@gmail.com
    - leeyingjie_95@hotmail.com

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

after_success:
    - mvn clean test DskipITs jacoco:report coveralls:report
